In [1]:
import pandas as pd

df = pd.read_csv('air_q_b_horizonte_centro.csv')
# https://medium.com/@filip.sekan/pivot-vs-pivot-table-methods-in-pandas-definitions-examples-differences-dcc9e14e667f

In [2]:
df.head()

,Estado,Município,Estação,Ano de Data,Mês de Data,Dia de Data,Data,IQAR,NumeroIQAR,Poluente,Tipo de cálculo,Tipo de monitoramento
0,MG,Belo Horizonte,Centro - Av. do Contorno,2021,dezembro,8,08/12/2021,DQA (Recomendação OMS),2,MP10,Média aritmética de 24h,Automática
1,MG,Belo Horizonte,Centro - Av. do Contorno,2020,agosto,22,22/08/2020,DQA (Recomendação OMS),2,MP10,Média aritmética de 24h,Automática
2,MG,Belo Horizonte,Centro - Av. do Contorno,2021,outubro,12,12/10/2021,DQA (Recomendação OMS),2,MP10,Média aritmética de 24h,Automática
3,MG,Belo Horizonte,Centro - Av. do Contorno,2021,novembro,12,12/11/2021,DQA (Recomendação OMS),3,MP10,Média aritmética de 24h,Automática
4,MG,Belo Horizonte,Centro - Av. do Contorno,2021,novembro,15,15/11/2021,DQA (Recomendação OMS),3,MP10,Média aritmética de 24h,Automática

In [3]:
poluentes = ['CO', 'MP10', 'O3', 'MP2.5', 'SO2']

df_filtrado = df[df['Poluente'].isin(poluentes)]

df_pivot = df_filtrado.pivot(index='Data', columns='Poluente', values='NumeroIQAR')

df_pivot = df_pivot.reindex(columns=poluentes)

df_pivot.reset_index(inplace=True)

In [4]:
df_pivot.head()

Poluente        Data   CO  MP10    O3  MP2.5  SO2
0         01/01/2015  NaN  12.0  54.0    NaN  8.0
1         01/01/2016  0.0  17.0  42.0    NaN  0.0
2         01/01/2018  NaN  26.0  29.0   10.0  0.0
3         01/01/2019  0.0  16.0  34.0    4.0  0.0
4         01/01/2020  0.0  11.0  40.0    NaN  2.0

In [5]:
df_pivot.to_csv('b_horizonte_pivot_centro.csv', index=False, encoding='utf-8-sig')