In [1]:
import pandas as pd

df = pd.read_csv('air_q_b_horizonte_amazonas.csv')
# https://medium.com/@filip.sekan/pivot-vs-pivot-table-methods-in-pandas-definitions-examples-differences-dcc9e14e667f

In [2]:
df.head(50)

,Estado,Município,Estação,Ano de Data,Mês de Data,Dia de Data,Data,IQAR,NumeroIQAR,Poluente,Tipo de cálculo,Tipo de monitoramento
0,MG,Belo Horizonte,Avenida Amazonas,2018,janeiro,27,27/01/2018,DQA (Recomendação OMS),0,CO,Máxima média de 8h,Automática
1,MG,Belo Horizonte,Avenida Amazonas,2018,janeiro,28,28/01/2018,DQA (Recomendação OMS),0,CO,Máxima média de 8h,Automática
2,MG,Belo Horizonte,Avenida Amazonas,2017,dezembro,24,24/12/2017,DQA (Recomendação OMS),0,CO,Máxima média de 8h,Automática
3,MG,Belo Horizonte,Avenida Amazonas,2017,dezembro,27,27/12/2017,DQA (Recomendação OMS),0,CO,Máxima média de 8h,Automática
4,MG,Belo Horizonte,Avenida Amazonas,2017,dezembro,28,28/12/2017,DQA (Recomendação OMS),0,CO,Máxima média de 8h,Automática
5,MG,Belo Horizonte,Avenida Amazonas,2017,dezembro,25,25/12/2017,DQA (Recomendação OMS),0,CO,Máxima média de 8h,Automática
6,MG,Belo Horizonte,Avenida Amazonas,2018,fevereiro,4,04/02/2018,DQA (Recomendação OMS),0,CO,Máxima média de 8h,Automática
7,MG,Belo Horizonte,Avenida Amazonas,2017,dezembro,26,26/12/2017,DQA (Recomendação OMS),0,CO,Máxima média de 8h,Automática
8,MG,Belo Horizonte,Avenida Amazonas,2017,dezembro,29,29/12/2017,DQA (Recomendação OMS),0,CO,Máxima média de 8h,Automática
9,MG,Belo Horizonte,Avenida Amazonas,2017,dezembro,20,20/12/2017,DQA (Recomendação OMS),0,CO,Máxima média de 8h,Automática
10,MG,Belo Horizonte,Avenida Amazonas,2018,janeiro,9,09/01/2018,DQA (Recomendação OMS),0,CO,Máxima média de 8h,Automática
11,MG,Belo Horizonte,Avenida Amazonas,2018,janeiro,17,17/01/2018,DQA (Recomendação OMS),0,CO,Máxima média de 8h,Automática
12,MG,Belo Horizonte,Avenida Amazonas,2018,janeiro,26,26/01/2018,DQA (Recomendação OMS),0,CO,Máxima média de 8h,Automática
13,MG,Belo Horizonte,Avenida Amazonas,2018,janeiro,23,23/01/2018,DQA (Recomendação OMS),0,CO,Máxima média de 8h,Automática
14,MG,Belo Horizonte,Avenida Amazonas,2018,janeiro,24,24/01/2018,DQA (Recomendação OMS),0,CO,Máxima média de 8h,Automática
15,MG,Belo Horizonte,Avenida Amazonas,2018,janeiro,8,08/01/2018,DQA (Recomendação OMS),0,CO,Máxima média de 8h,Automática
16,MG,Belo Horizonte,Avenida Amazonas,2017,dezembro,18,18/12/2017,DQA (Recomendação OMS),0,CO,Máxima média de 8h,Automática
17,MG,Belo Horizonte,Avenida Amazonas,2017,dezembro,19,19/12/2017,DQA (Recomendação OMS),0,CO,Máxima média de 8h,Automática
18,MG,Belo Horizonte,Avenida Amazonas,2018,fevereiro,15,15/02/2018,DQA (Recomendação OMS),0,CO,Máxima média de 8h,Automática
19,MG,Belo Horizonte,Avenida Amazonas,2018,janeiro,13,13/01/2018,DQA (Recomendação OMS),0,CO,Máxima média de 8h,Automática
20,MG,Belo Horizonte,Avenida Amazonas,2018,janeiro,18,18/01/2018,DQA (Recomendação OMS),0,CO,Máxima média de 8h,Automática
21,MG,Belo Horizonte,Avenida Amazonas,2018,fevereiro,14,14/02/2018,DQA (Recomendação OMS),0,CO,Máxima média de 8h,Automática
22,MG,Belo Horizonte,Avenida Amazonas,2017,dezembro,23,23/12/2017,DQA (Recomendação OMS),0,CO,Máxima média de 8h,Automática
23,MG,Belo Horizonte,Avenida Amazonas,2018,janeiro,12,12/01/2018,DQA (Recomendação OMS),0,CO,Máxima média de 8h,Automática
24,MG,Belo Horizonte,Avenida Amazonas,2018,janeiro,21,21/01/2018,DQA (Recomendação OMS),0,CO,Máxima média de 8h,Automática
25,MG,Belo Horizonte,Avenida Amazonas,2018,fevereiro,16,16/02/2018,DQA (Recomendação OMS),0,CO,Máxima média de 8h,Automática
26,MG,Belo Horizonte,Avenida Amazonas,2018,fevereiro,17,17/02/2018,DQA (Recomendação OMS),0,CO,Máxima média de 8h,Automática
27,MG,Belo Horizonte,Avenida Amazonas,2018,fevereiro,18,18/02/2018,DQA (Recomendação OMS),0,CO,Máxima média de 8h,Automática
28,MG,Belo Horizonte,Avenida Amazonas,2018,janeiro,7,07/01/2018,DQA (Recomendação OMS),0,CO,Máxima média de 8h,Automática
29,MG,Belo Horizonte,Avenida Amazonas,2018,janeiro,20,20/01/2018,DQA (Recomendação OMS),0,CO,Máxima média de 8h,Automática
30,MG,Belo Horizonte,Avenida Amazonas,2018,fevereiro,12,12/02/2018,DQA (Recomendação OMS),0,CO,Máxima média de 8h,Automática
31,MG,Belo Horizonte,Avenida Amazonas,2017,dezembro,13,13/12/2017,DQA (Recomendação OMS),0,CO,Máxima média de 8h,Automática
32,MG,Belo Horizonte,Avenida Amazonas,2017,dezembro,14,14/12/2017,DQA (Recomendação OMS),0,CO,Máxima média de 8h,Automática
33,MG,Belo Horizonte,Avenida Amazonas,2018,janeiro,29,29/01/2018,DQA (Recomendação OMS),0,CO,Máxima média de 8h,Automática
34,MG,Belo Horizonte,Avenida Amazonas,2018,fevereiro,13,13/02/2018,DQA (Recomendação OMS),0,CO,Máxima média de 8h,Automática
35,MG,Belo Horizonte,Avenida Amazonas,2017,dezembro,22,22/12/2017,DQA (Recomendação OMS),0,CO,Máxima média de 8h,Automática
36,MG,Belo Horizonte,Avenida Amazonas,2018,janeiro,16,16/01/2018,DQA (Recomendação OMS),0,CO,Máxima média de 8h,Automática
37,MG,Belo Horizonte,Avenida Amazonas,2018,janeiro,19,19/01/2018,DQA (Recomendação OMS),0,CO,Máxima média de 8h,Automática
38,MG,Belo Horizonte,Avenida Amazonas,2018,janeiro,15,15/01/2018,DQA (Recomendação OMS),0,CO,Máxima média de 8h,Automática
39,MG,Belo Horizonte,Avenida Amazonas,2018,fevereiro,25,25/02/2018,DQA (Recomendação OMS),0,CO,Máxima média de 8h,Automática
40,MG,Belo Horizonte,Avenida Amazonas,2018,janeiro,2,02/01/2018,DQA (Recomendação OMS),0,CO,Máxima média de 8h,Automática
41,MG,Belo Horizonte,Avenida Amazonas,2018,março,25,25/03/2018,DQA (Recomendação OMS),0,CO,Máxima média de 8h,Automática
42,MG,Belo Horizonte,Avenida Amazonas,2018,março,31,31/03/2018,DQA (Recomendação OMS),0,CO,Máxima média de 8h,Automática
43,MG,Belo Horizonte,Avenida Amazonas,2018,fevereiro,9,09/02/2018,DQA (Recomendação OMS),0,CO,Máxima média de 8h,Automática
44,MG,Belo Horizonte,Avenida Amazonas,2018,março,24,24/03/2018,DQA (Recomendação OMS),0,CO,Máxima média de 8h,Automática
45,MG,Belo Horizonte,Avenida Amazonas,2018,abril,1,01/04/2018,DQA (Recomendação OMS),0,CO,Máxima média de 8h,Automática
46,MG,Belo Horizonte,Avenida Amazonas,2017,dezembro,31,31/12/2017,DQA (Recomendação OMS),0,CO,Máxima média de 8h,Automática
47,MG,Belo Horizonte,Avenida Amazonas,2018,janeiro,3,03/01/2018,DQA (Recomendação OMS),0,CO,Máxima média de 8h,Automática
48,MG,Belo Horizonte,Avenida Amazonas,2018,fevereiro,5,05/02/2018,DQA (Recomendação OMS),0,CO,Máxima média de 8h,Automática
49,MG,Belo Horizonte,Avenida Amazonas,2018,março,30,30/03/2018,DQA (Recomendação OMS),0,CO,Máxima média de 8h,Automática

In [3]:
df_filtered_SO2 = df[df['Poluente'] == 'SO2'].copy()

In [4]:
df_filtered_SO2.head()

,Estado,Município,Estação,Ano de Data,Mês de Data,Dia de Data,Data,IQAR,NumeroIQAR,Poluente,Tipo de cálculo,Tipo de monitoramento
1167,MG,Belo Horizonte,Avenida Amazonas,2020,dezembro,1,01/12/2020,Moderada,43,SO2,Média aritmética de 24h,Automática
1168,MG,Belo Horizonte,Avenida Amazonas,2020,dezembro,3,03/12/2020,Moderada,43,SO2,Média aritmética de 24h,Automática
1169,MG,Belo Horizonte,Avenida Amazonas,2020,dezembro,5,05/12/2020,Moderada,43,SO2,Média aritmética de 24h,Automática
1170,MG,Belo Horizonte,Avenida Amazonas,2020,dezembro,4,04/12/2020,Moderada,45,SO2,Média aritmética de 24h,Automática
1171,MG,Belo Horizonte,Avenida Amazonas,2015,março,25,25/03/2015,Moderada,57,SO2,Média aritmética de 24h,Automática

In [5]:
df['IQAR'].unique()

array(['DQA (Recomendação OMS)', 'Moderada', 'Boa', 'Ruim', 'Muito ruim'],
      dtype=object)

In [6]:
poluentes = ['CO', 'MP10', 'O3', 'MP2.5', 'SO2']

df_filtrado = df[df['Poluente'].isin(poluentes)]

df_pivot = df_filtrado.pivot(index='Data', columns='Poluente', values='NumeroIQAR')

df_pivot = df_pivot.reindex(columns=poluentes)

df_pivot.reset_index(inplace=True)

In [7]:
df_pivot.head()

Poluente        Data   CO  MP10    O3  MP2.5   SO2
0         01/01/2015  0.0   NaN  68.0    NaN  82.0
1         01/01/2016  1.0  26.0   NaN   32.0   6.0
2         01/01/2018  0.0   NaN  39.0    NaN  10.0
3         01/01/2019  1.0  10.0   NaN    NaN  16.0
4         01/01/2020  0.0   NaN   NaN    6.0   NaN

In [8]:
df_pivot['Data'] = pd.to_datetime(df_pivot['Data'], format='%d/%m/%Y')
df_pivot.sort_values(by='Data', inplace=True)

In [9]:
df_pivot_filtered = df_pivot[df_pivot['SO2'].notna()]

In [10]:
df_pivot.head(50)

Poluente       Data   CO  MP10    O3  MP2.5   SO2
0        2015-01-01  0.0   NaN  68.0    NaN  82.0
70       2015-01-02  0.0   NaN  79.0    NaN  83.0
140      2015-01-03  0.0   NaN  44.0    NaN  83.0
210      2015-01-04  0.0   NaN  49.0    NaN  82.0
281      2015-01-05  0.0   NaN  59.0    NaN  82.0
353      2015-01-06  0.0   NaN  54.0    NaN  82.0
426      2015-01-07  0.0   NaN  54.0    NaN  82.0
500      2015-01-08  NaN   NaN  66.0    NaN  82.0
574      2015-01-09  NaN   NaN  61.0    NaN  82.0
648      2015-01-10  NaN   NaN  51.0    NaN  82.0
722      2015-01-11  0.0   NaN  70.0    NaN  82.0
796      2015-01-12  0.0  26.0  76.0    NaN  82.0
870      2015-01-13  0.0  26.0   NaN    NaN   NaN
944      2015-01-14  NaN  26.0   NaN    NaN   NaN
1017     2015-01-15  NaN  24.0   NaN    NaN   NaN
1090     2015-01-16  0.0  25.0   NaN    NaN   NaN
1163     2015-01-17  0.0  22.0   NaN    NaN   NaN
1236     2015-01-18  0.0  19.0   NaN    NaN   NaN
1308     2015-01-19  0.0  24.0   NaN    NaN   NaN
1379     2015-01-20  0.0  27.0   NaN    NaN   NaN
1451     2015-01-21  0.0  31.0   NaN    NaN   NaN
1523     2015-01-22  0.0  25.0   NaN    NaN   NaN
1594     2015-01-23  0.0  23.0   NaN    NaN   NaN
1665     2015-01-24  0.0  19.0   NaN    NaN   NaN
1736     2015-01-25  0.0  20.0   NaN    NaN   NaN
1807     2015-01-26  0.0  29.0   NaN    NaN   NaN
1879     2015-01-27  1.0  32.0   NaN    NaN   NaN
1950     2015-01-28  0.0  29.0   NaN    NaN   NaN
2022     2015-01-29  0.0  34.0   NaN    NaN   NaN
2091     2015-01-30  0.0  30.0   NaN    NaN   NaN
2156     2015-01-31  0.0  27.0   NaN    NaN   NaN
6        2015-02-01  0.0  22.0   NaN    NaN   NaN
76       2015-02-02  0.0  24.0   NaN    NaN   NaN
146      2015-02-03  0.0  22.0   NaN    NaN   NaN
216      2015-02-04  0.0  27.0   NaN    NaN   NaN
288      2015-02-05  0.0  25.0   NaN    NaN   NaN
360      2015-02-06  0.0  28.0   NaN    NaN   NaN
433      2015-02-07  0.0  16.0   NaN    NaN   NaN
507      2015-02-08  0.0  10.0   NaN    NaN   NaN
581      2015-02-09  0.0  24.0   NaN    NaN   NaN
654      2015-02-10  0.0  19.0   NaN    NaN   NaN
728      2015-02-11  NaN  18.0   NaN    NaN   NaN
802      2015-02-12  0.0  22.0   NaN    NaN   NaN
876      2015-02-13  0.0  22.0   NaN    NaN   NaN
950      2015-02-14  0.0  17.0   NaN    NaN   NaN
1023     2015-02-15  NaN  14.0   NaN    NaN   NaN
1096     2015-02-16  0.0  17.0   NaN    NaN   NaN
1169     2015-02-17  0.0  18.0   NaN    NaN   NaN
1242     2015-02-18  NaN  18.0   NaN    NaN   NaN
1314     2015-02-19  1.0  31.0   NaN    NaN   NaN

In [11]:
df_pivot_filtered.head(50)

Poluente       Data   CO  MP10     O3  MP2.5   SO2
0        2015-01-01  0.0   NaN   68.0    NaN  82.0
70       2015-01-02  0.0   NaN   79.0    NaN  83.0
140      2015-01-03  0.0   NaN   44.0    NaN  83.0
210      2015-01-04  0.0   NaN   49.0    NaN  82.0
281      2015-01-05  0.0   NaN   59.0    NaN  82.0
353      2015-01-06  0.0   NaN   54.0    NaN  82.0
426      2015-01-07  0.0   NaN   54.0    NaN  82.0
500      2015-01-08  NaN   NaN   66.0    NaN  82.0
574      2015-01-09  NaN   NaN   61.0    NaN  82.0
648      2015-01-10  NaN   NaN   51.0    NaN  82.0
722      2015-01-11  0.0   NaN   70.0    NaN  82.0
796      2015-01-12  0.0  26.0   76.0    NaN  82.0
1746     2015-03-25  0.0  17.0   44.0    NaN  57.0
1817     2015-03-26  0.0  24.0   42.0    NaN  68.0
1888     2015-03-27  0.0  30.0   66.0    NaN  76.0
1960     2015-03-28  0.0  22.0   97.0    NaN  76.0
2029     2015-03-29  0.0  23.0   72.0    NaN  78.0
2096     2015-03-30  1.0  37.0   72.0    NaN  81.0
2161     2015-03-31  1.0  34.0   45.0    NaN  82.0
16       2015-04-01  1.0  30.0   79.0    NaN  82.0
86       2015-04-02  0.0  15.0   76.0    NaN  82.0
156      2015-04-03  0.0  13.0   73.0    NaN  78.0
227      2015-04-04  0.0  11.0   70.0    NaN  78.0
299      2015-04-05  0.0  18.0   44.0    NaN  74.0
372      2015-04-06  0.0  29.0   66.0    NaN  74.0
444      2015-04-07  0.0  21.0   55.0    NaN  80.0
518      2015-04-08  NaN  10.0   47.0    NaN  70.0
593      2015-04-09  NaN  13.0   54.0    NaN  59.0
666      2015-04-10  0.0  14.0   62.0    NaN  62.0
740      2015-04-11  0.0  17.0   70.0    NaN  64.0
814      2015-04-12  0.0  16.0   50.0    NaN  66.0
888      2015-04-13  0.0  22.0   70.0    NaN  64.0
962      2015-04-14  0.0  24.0   66.0    NaN  66.0
1035     2015-04-15  0.0  26.0   74.0    NaN  64.0
1108     2015-04-16  1.0  30.0   50.0    NaN  72.0
1181     2015-04-17  1.0  24.0   75.0    NaN  72.0
1253     2015-04-18  0.0  24.0   66.0    NaN  68.0
1324     2015-04-19  0.0  22.0   79.0    NaN  70.0
1396     2015-04-20  0.0  28.0   72.0    NaN  70.0
1468     2015-04-21  0.0  34.0  141.0    NaN  74.0
1539     2015-04-22  0.0  23.0  119.0    NaN  74.0
1610     2015-04-23  0.0  16.0   82.0    NaN  70.0
1681     2015-04-24  0.0  26.0   60.0    NaN  70.0
1752     2015-04-25  0.0  26.0   63.0    NaN  81.0
1823     2015-04-26  NaN  11.0   66.0    NaN  76.0
1894     2015-04-27  NaN  14.0   62.0    NaN  70.0
1966     2015-04-28  0.0  21.0   69.0    NaN  72.0
2035     2015-04-29  0.0  25.0   62.0    NaN  72.0
2102     2015-04-30  0.0  22.0   67.0    NaN  66.0
22       2015-05-01  0.0  20.0   69.0    NaN  66.0

In [12]:
df_pivot_filtered.tail(50)

Poluente       Data   CO  MP10  O3  MP2.5   SO2
863      2020-11-12  0.0  18.0 NaN   12.0  38.0
937      2020-11-13  0.0  20.0 NaN   12.0  38.0
1010     2020-11-14  0.0  16.0 NaN   10.0  38.0
1083     2020-11-15  0.0  16.0 NaN    9.0  36.0
1156     2020-11-16  0.0  22.0 NaN   26.0  38.0
1229     2020-11-17  0.0  20.0 NaN   10.0  38.0
1301     2020-11-18  NaN  14.0 NaN   10.0  38.0
1372     2020-11-19  0.0  22.0 NaN   11.0  38.0
1444     2020-11-20  0.0  16.0 NaN   10.0  40.0
1516     2020-11-21  NaN   7.0 NaN    6.0  38.0
1587     2020-11-22  NaN   8.0 NaN    6.0  38.0
1658     2020-11-23  NaN   9.0 NaN    7.0  38.0
1729     2020-11-24  NaN   9.0 NaN    6.0  38.0
1800     2020-11-25  NaN  10.0 NaN    6.0  38.0
1872     2020-11-26  NaN   8.0 NaN    7.0  38.0
1943     2020-11-27  NaN  10.0 NaN    6.0  38.0
2015     2020-11-28  NaN   8.0 NaN    6.0  40.0
2084     2020-11-29  NaN   6.0 NaN    5.0  40.0
2150     2020-11-30  NaN  12.0 NaN    8.0  40.0
69       2020-12-01  0.0  20.0 NaN   11.0  43.0
139      2020-12-02  NaN  18.0 NaN   11.0  40.0
209      2020-12-03  0.0  23.0 NaN   27.0  43.0
280      2020-12-04  0.0  29.0 NaN   34.0  45.0
352      2020-12-05  0.0  14.0 NaN   10.0  43.0
425      2020-12-06  NaN   9.0 NaN    7.0  43.0
499      2020-12-07  NaN  15.0 NaN   10.0  43.0
573      2020-12-08  0.0  15.0 NaN   10.0  43.0
647      2020-12-09  0.0  14.0 NaN   10.0  43.0
721      2020-12-10  0.0  19.0 NaN   12.0  43.0
795      2020-12-11  0.0  18.0 NaN    9.0  43.0
869      2020-12-12  0.0  10.0 NaN    8.0  43.0
943      2020-12-13  NaN  10.0 NaN    7.0  43.0
1016     2020-12-14  NaN  11.0 NaN    8.0  43.0
1089     2020-12-15  0.0  15.0 NaN    9.0  43.0
1162     2020-12-16  NaN  15.0 NaN    9.0  43.0
1235     2020-12-17  NaN  12.0 NaN    8.0  43.0
1307     2020-12-18  0.0  18.0 NaN   11.0  45.0
1378     2020-12-19  0.0  14.0 NaN   10.0  43.0
1450     2020-12-20  0.0  10.0 NaN    7.0  43.0
1522     2020-12-21  NaN  12.0 NaN    9.0  43.0
1593     2020-12-22  0.0  12.0 NaN    8.0  43.0
1664     2020-12-23  NaN  16.0 NaN   10.0  45.0
1735     2020-12-24  NaN   9.0 NaN    8.0  43.0
1806     2020-12-25  NaN   8.0 NaN    6.0  43.0
1878     2020-12-26  NaN   8.0 NaN    6.0  43.0
1949     2020-12-27  NaN   7.0 NaN    7.0  43.0
2021     2020-12-28  NaN  10.0 NaN    NaN  43.0
2090     2020-12-29  NaN  11.0 NaN    NaN  43.0
2155     2020-12-30  NaN  11.0 NaN    9.0  43.0
2196     2020-12-31  NaN  13.0 NaN   10.0  43.0